spring:
  profiles:
    include: real-db
  jpa:
    properties:
      hibernate:
        storage_engine: innodb
        globally_quoted_identifiers: true
    open-in-view: false

server:
  servlet:
    encoding:
      force-response: true